insert into Lingua (id, nome, descrizione) values(0, 'Lingua cinese', '<div style="text-align: justify;">Il cinese mandarino è la lingua principalmente parlata in Cina ed ha 4 toni. Questo sito tratterà principalmente il <strong>cinese semplificato</strong>.<p>La differenza tra il cinese tradizionale ed il cinese semplificato risiede nella scrittura, infatti nel cinese tradizionale i caratteri risultano più complessi ed hanno più tratti.</p><ul style="text-align: center; list-style: none; gap: 1.5rem;  margin-bottom: 4rem;">Es.<c class="lxgw-wenkai-tc-regular" style="font-size: 3rem;"><li>媽 -> 妈</li><li>語 -> 语</li><li>環 -> 环</li><li>區 -> 区</li><li>體 -> 体</li><li>長 -> 长</li></ul></c><p>Non vi sono invece differenze sulla pronuncia.</p><p>Rispetto a molte altre lingue, il cinese, come anche il giapponese e il coreano, non presentano spazi tra i caratteri e pertanto è necessario già conoscere la parola a memoria.</p></div>');

insert into Glossario (id, nome) values(0, 'Glossario di lingua cinese');

insert into Vocabolo (id, nome, traduzione, pinyin) values(0, '中', 'centro', 'zhōng');
insert into Vocabolo (id, nome, traduzione, pinyin) values(1, '中文', 'lingua cinese', 'zhōngwén');

insert into Vocabolo (id, nome, traduzione, pinyin) values(3, '谢谢', 'grazie', 'xiè xie');
insert into Vocabolo (id, nome, traduzione, pinyin) values(4, '吧', '*per affermazioni \\ imperativo*', 'ba');
insert into Vocabolo (id, nome, traduzione, pinyin) values(5, '棒', 'forte', 'bàng');
insert into Vocabolo (id, nome, traduzione, pinyin) values(6, '不', 'non', 'bù');
insert into Vocabolo (id, nome, traduzione, pinyin) values(7, '不错', 'non male', 'búcuò');
insert into Vocabolo (id, nome, traduzione, pinyin) values(8, '词典', 'dizionario', 'cí diǎn');
insert into Vocabolo (id, nome, traduzione, pinyin) values(9, '大', 'gande', 'dà');
insert into Vocabolo (id, nome, traduzione, pinyin) values(10, '大学', 'università', 'dàxué');
insert into Vocabolo (id, nome, traduzione, pinyin) values(11, '的', 'di', 'de');
insert into Vocabolo (id, nome, traduzione, pinyin) values(12, '对', 'esatto', 'duì');
insert into Vocabolo (id, nome, traduzione, pinyin) values(13, '法国', 'Francia', 'fǎ guó');
insert into Vocabolo (id, nome, traduzione, pinyin) values(14, '法国人', 'francese *cittadino', 'fǎ guó rén');
insert into Vocabolo (id, nome, traduzione, pinyin) values(15, '法语', 'francese *lingua', 'fǎ  yǔ');
insert into Vocabolo (id, nome, traduzione, pinyin) values(16, '风', 'vento/notizia', 'fēng');
insert into Vocabolo (id, nome, traduzione, pinyin) values(17, '高', 'alto', 'gāo');
insert into Vocabolo (id, nome, traduzione, pinyin) values(18, '高兴', 'contento', 'gāoxìng');
insert into Vocabolo (id, nome, traduzione, pinyin) values(19, '贵', 'prezioso/costoso/*forma di cortesia*', 'guì');
insert into Vocabolo (id, nome, traduzione, pinyin) values(20, '国', 'paese', 'guó');
insert into Vocabolo (id, nome, traduzione, pinyin) values(21, '嗨', 'ciao', 'hāi');
insert into Vocabolo (id, nome, traduzione, pinyin) values(22, '还好', 'abbastanza bene', 'hái hǎo');
insert into Vocabolo (id, nome, traduzione, pinyin) values(23, '还可以', 'va bene', 'hái kěyǐ');
insert into Vocabolo (id, nome, traduzione, pinyin) values(24, '汉语', 'cinese *lingua', 'hàn yǔ');
insert into Vocabolo (id, nome, traduzione, pinyin) values(25, '好看', 'bello', 'hǎo kàn');
insert into Vocabolo (id, nome, traduzione, pinyin) values(26, '好客', 'ospitale', 'hào kè');
insert into Vocabolo (id, nome, traduzione, pinyin) values(27, '很', 'molto', 'hěn');
insert into Vocabolo (id, nome, traduzione, pinyin) values(28, '和平', 'pace', 'hépíng');
insert into Vocabolo (id, nome, traduzione, pinyin) values(29, '见', 'vedere', 'jiàn');
insert into Vocabolo (id, nome, traduzione, pinyin) values(30, '叫', 'chiamarsi/chiamare', 'jiào');
insert into Vocabolo (id, nome, traduzione, pinyin) values(31, '经理', 'direttore', 'jīnglǐ');
insert into Vocabolo (id, nome, traduzione, pinyin) values(32, '兰', 'orchidea', 'lán');
insert into Vocabolo (id, nome, traduzione, pinyin) values(33, '老', 'vecchio', 'lǎo');
insert into Vocabolo (id, nome, traduzione, pinyin) values(34, '老人', 'anziano/a', 'lǎo rén');
insert into Vocabolo (id, nome, traduzione, pinyin) values(35, '老师', 'professore/maestro', 'lǎo shī');
insert into Vocabolo (id, nome, traduzione, pinyin) values(36, '路', 'strada', 'lù');
insert into Vocabolo (id, nome, traduzione, pinyin) values(37, '妈妈', 'mamma', 'māma');
insert into Vocabolo (id, nome, traduzione, pinyin) values(38, '马', 'cavallo', 'mǎ');
insert into Vocabolo (id, nome, traduzione, pinyin) values(39, '吗', '*per domande*', 'ma');
insert into Vocabolo (id, nome, traduzione, pinyin) values(40, '美', 'bello', 'měi');
insert into Vocabolo (id, nome, traduzione, pinyin) values(41, '美国', 'USA', 'měi guó');
insert into Vocabolo (id, nome, traduzione, pinyin) values(42, '美国人', 'americano *cittadino', 'měi guó rén');
insert into Vocabolo (id, nome, traduzione, pinyin) values(43, '米', 'riso', 'mǐ');
insert into Vocabolo (id, nome, traduzione, pinyin) values(44, '面', 'farina/noodle', 'miàn');
insert into Vocabolo (id, nome, traduzione, pinyin) values(45, '名字', 'nome', 'míng zi');
insert into Vocabolo (id, nome, traduzione, pinyin) values(46, '哪', 'quale', 'nǎ');
insert into Vocabolo (id, nome, traduzione, pinyin) values(47, '哪儿', 'dove', 'nǎr');
insert into Vocabolo (id, nome, traduzione, pinyin) values(48, '那', 'quello', 'nà');
insert into Vocabolo (id, nome, traduzione, pinyin) values(49, '呢', '*per domande*', 'ne');
insert into Vocabolo (id, nome, traduzione, pinyin) values(50, '你好', 'ciao', 'nǐ hǎo');
insert into Vocabolo (id, nome, traduzione, pinyin) values(51, '你们好', 'ciao *a più persone*', 'nǐ men hǎo');
insert into Vocabolo (id, nome, traduzione, pinyin) values(52, '您好', 'salve', 'nín hǎo');
insert into Vocabolo (id, nome, traduzione, pinyin) values(53, '请问', 'scusi  *per il disturbo*', 'qǐngwèn');
insert into Vocabolo (id, nome, traduzione, pinyin) values(54, '认识', 'conoscere', 'rènshi');
insert into Vocabolo (id, nome, traduzione, pinyin) values(55, '日本', 'Giappone', 'rì běn');
insert into Vocabolo (id, nome, traduzione, pinyin) values(56, '日本人', 'giapponese *cittadino', 'rì běn rén');
insert into Vocabolo (id, nome, traduzione, pinyin) values(57, '日语', 'giapponese *lingua', 'rì yǔ');
insert into Vocabolo (id, nome, traduzione, pinyin) values(58, '赛马', 'corsa dei cavalli', 'sài mǎ');
insert into Vocabolo (id, nome, traduzione, pinyin) values(59, '赛马节', 'festa della corsa dei cavalli', 'sài mǎ jié');
insert into Vocabolo (id, nome, traduzione, pinyin) values(60, '帅', 'bello', 'shuài');
insert into Vocabolo (id, nome, traduzione, pinyin) values(61, '山', 'montagna', 'shān');
insert into Vocabolo (id, nome, traduzione, pinyin) values(62, '谁', 'chi *domanda*', 'shéi');
insert into Vocabolo (id, nome, traduzione, pinyin) values(63, '什么', 'cosa *per chiedere*', 'shénme');
insert into Vocabolo (id, nome, traduzione, pinyin) values(64, '是', 'essere', 'shì');
insert into Vocabolo (id, nome, traduzione, pinyin) values(65, '王', 're', 'wáng');
insert into Vocabolo (id, nome, traduzione, pinyin) values(66, '王国', 'regno', 'wáng guó');
insert into Vocabolo (id, nome, traduzione, pinyin) values(67, '网', 'rete/internet', 'wǎng');
insert into Vocabolo (id, nome, traduzione, pinyin) values(68, '网名', 'nickname', 'wǎng  míng');
insert into Vocabolo (id, nome, traduzione, pinyin) values(69, '先生', 'signore', 'xiānsheng');
insert into Vocabolo (id, nome, traduzione, pinyin) values(70, '小', 'piccolo', 'xiǎo');
insert into Vocabolo (id, nome, traduzione, pinyin) values(71, '小姐', 'signorina', 'xiǎojiě');
insert into Vocabolo (id, nome, traduzione, pinyin) values(72, '小时', 'ora', 'xiǎo shí');
insert into Vocabolo (id, nome, traduzione, pinyin) values(73, '小学', 'scuola elementare', 'xiǎo xué');
insert into Vocabolo (id, nome, traduzione, pinyin) values(74, '西班牙', 'Spagna', 'xī bān yá');
insert into Vocabolo (id, nome, traduzione, pinyin) values(75, '西班牙人', 'spagnolo *cittadino', 'xī bān yá rén');
insert into Vocabolo (id, nome, traduzione, pinyin) values(76, '西班牙文', 'spagnolo *lingua', 'xī bān yá wén');
insert into Vocabolo (id, nome, traduzione, pinyin) values(77, '西班牙语', 'spagnolo *lingua', 'xī bān yá yǔ');
insert into Vocabolo (id, nome, traduzione, pinyin) values(78, '姓', 'fare di cognome', 'xìng');
insert into Vocabolo (id, nome, traduzione, pinyin) values(79, '学', 'studiare', 'xué');
insert into Vocabolo (id, nome, traduzione, pinyin) values(80, '学生', 'studente', 'xuéshēng');
insert into Vocabolo (id, nome, traduzione, pinyin) values(81, '学习', 'studiare', 'xuéxí');
insert into Vocabolo (id, nome, traduzione, pinyin) values(82, '亚', 'Asia', 'yà');
insert into Vocabolo (id, nome, traduzione, pinyin) values(83, '亚洲', 'Asia', 'yàzhōu');
insert into Vocabolo (id, nome, traduzione, pinyin) values(84, '也', 'anche', 'yě');
insert into Vocabolo (id, nome, traduzione, pinyin) values(85, '意大利', 'Italia', 'yìdàlì');
insert into Vocabolo (id, nome, traduzione, pinyin) values(86, '意大利人', 'italiano *cittadino', 'yìdàlìrén');
insert into Vocabolo (id, nome, traduzione, pinyin) values(87, '意大利语', 'italiano *lingua', 'yìdàlìyǔ');
insert into Vocabolo (id, nome, traduzione, pinyin) values(88, '意大利面', 'spaghetti o pasta', 'yìdàlì miàn');
insert into Vocabolo (id, nome, traduzione, pinyin) values(89, '英国', 'UK', 'yīngguó');
insert into Vocabolo (id, nome, traduzione, pinyin) values(90, '英国人', 'inglese *cittadino', 'yīngguórén');
insert into Vocabolo (id, nome, traduzione, pinyin) values(91, '英语', 'inglese *lingua', 'yīngyǔ');
insert into Vocabolo (id, nome, traduzione, pinyin) values(92, '用', 'usare', 'yòng');
insert into Vocabolo (id, nome, traduzione, pinyin) values(93, '有意思', 'divertente', 'yǒuyìsi');
insert into Vocabolo (id, nome, traduzione, pinyin) values(94, '做', 'fare', 'zuò');

insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,0);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,1);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,3);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,4);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,5);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,6);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,7);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,8);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,9);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,10);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,11);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,12);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,13);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,14);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,15);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,16);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,17);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,18);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,19);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,20);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,21);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,22);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,23);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,24);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,25);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,26);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,27);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,28);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,29);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,30);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,31);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,32);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,33);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,34);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,35);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,36);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,37);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,38);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,39);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,40);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,41);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,42);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,43);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,44);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,45);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,46);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,47);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,48);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,49);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,50);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,51);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,52);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,53);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,54);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,55);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,56);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,57);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,58);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,59);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,60);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,61);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,62);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,63);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,64);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,65);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,66);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,67);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,68);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,69);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,70);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,71);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,72);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,73);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,74);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,75);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,76);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,77);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,78);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,79);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,80);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,81);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,82);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,83);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,84);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,85);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,86);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,87);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,88);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,89);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,90);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,91);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,92);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,93);
insert into glossario_vocaboli (glossario_id, vocaboli_id) values(0,94);




insert into regola_grammaticale (id, nome, descrizione_breve, descrizione, livello) values(nextval('regola_grammaticale_seq'), 'Ordine delle parole (SVO)', 'Soggetto + Verbo + Oggetto', 'Odine delle frase in cinese: Soggetto + Verbo + Oggetto', 'PRINCIPIANTE');

insert into testo (id, titolo, testo, livello) values(nextval('testo_seq'), '你好吗？', '你好吗？ 我很好。', 'PRINCIPIANTE');
